# 1) 本番ビルド／プレビュー設定
[build]
  publish   = "liff"
  functions = "functions"

# 2) ローカル開発（netlify dev）設定
[dev]
  publish   = "liff"
  functions = "functions"

# 3) Functions 外のすべてを index.html（SPA）にフォールバック
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = true
